version: "3.6"
services:
  database:
    environment:
      POSTGRES_DB: ddev
      POSTGRES_PASSWORD_FILE: /ddev/secrets/postgres-password
    image: ${dockerID}/ddev_db
    build:
      context: database
    restart: always
    secrets:
    - source: postgres-password
      target: /ddev/secrets/postgres-password
    volumes:
    - postgres-data:/var/lib/postgresql/data
  apiserver:
    build:
      context: api
      dockerfile: Dockerfile.api
    image: ${dockerID}/ddev_api
    volumes:
      - ./api:/usr/src/ddev
    ports:
      - "8080:8080"
      - "5005:5005"
    secrets:
      - source: postgres-password
        target: /ddev/secrets/postgres_password
    environment:
      SPRING_PROFILES_ACTIVE: postgres
  watcher:
    build:
      context: api
      dockerfile: Dockerfile.api
    volumes:
      - ./api:/usr/src/ddev
    command: mvn fizzed-watcher:run

volumes:
  postgres-data: {}
secrets:
  postgres-password:
    file: devsecrets/postgres_password
