version: "3.6"
services:
  database:
    environment:
      POSTGRES_DB: ddev
      POSTGRES_PASSWORD_FILE: /ddev/secrets/postgres-password
    image: pets-db:1.0
    restart: always
    secrets:
    - source: postgres-password
      target: /ddev/secrets/postgres-password
    volumes:
    - postgres-data:/var/lib/postgresql/data
  api:
    image: pets-api:1.0
    secrets:
    - source: postgres-password
      target: /ddev/secrets/postgres_password
    environment:
      SPRING_PROFILES_ACTIVE: postgres
  ui:
    build:
      context: ui
      dockerfile: Dockerfile-dev
    image: ${dockerID}/ddev_ui
    volumes:
      - ./ui/src:/app/src
      - ./ui/package.json:/app/package.json
    ports:
    - "3000:3000"
volumes:
  postgres-data: {}
secrets:
  postgres-password:
    file: devsecrets/postgres_password
